### ISSUE TITLE
Using MULTICOM_qa for ranking antibody-antigen docking

### ISSUE THREAD

**Issue by GuillaumeH-GR** [BioinfoMachineLearning/MULTICOM_qa#3]
Hello,

First, congratulations for your results with MULTICOM_qa at CASP15 and your associated preprint paper ! 

Considering I have a structural model of the Fv of one antibody (VH and VL domain oriented) and a structural model of the antigen, can you please tell me if you think it's possible to use MULTICOM_qa for ranking antibody-antigen docking ? My theoretical inputs would be : 

FASTA file : 
> VH chain sequence 
XXXXXXXXXXXXXXXXXXXXXXXXXXX
> VL chain sequence
YYYYYYYYYYYYYYYYYYYYYYYYYYYYY
> Antigen sequence
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

Directory path with Fv-antigen dockings

Stoichiometry : A1B1C1 

Directory path with individual structural models of the VH, the VL and the antigen.

Also, do we need to give a certain name to the chains of .pdb files ?

Thank you for your work and your consideration, 

Guillaume H

**Comment by RajShekhorRoy** [comment]
Hi,

Thanks for your kind words!!

Yes, I believe it is possible to do the ranking antibody-antigen docking and your input formats are correct too. And you do not need to give any special names to the chains of .pdb files as they will be detected automatically based on the sequence information that you are providing. 

Regards,
Raj.

**Comment by GuillaumeH-GR** [comment]
Thank you for you answer ! 

Great, I'll try it with some antibody-antigen docking models ! :)

Best regards, 

Guillaume H
